server:
  port: 8082

spring:
  application:
    name: client-order
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8866/eureka/

client-product: #服务名
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

feign:
  hystrix:
    enabled: true